### ISSUE TITLE
Usage

### ISSUE THREAD

**Issue by MrNGS** [martemyev/incompressible-flow#1]
Dear,
I've been looking for something like this for a year! Thank you very much indeed!
I hope it is still maintained. I wll go through it for a deep read. I wll come back when having questions.
Thank you.

**Comment by martemyev** [comment]
Hi,
It is maintained in a sense that I can help with building and running the code, but I'm afraid I didn't touch the code for too long to be able to add new features.
Cheers,
Mikhail
